In [1]:
import pandas as pd
import numpy as np
# pd.options.display.float_format = '{:.2f}'.format
# permite a visualização de 50 colunas no dataframe e coloca os valores float com 2 pontos decimais
import pyarrow as pa
import pyarrow.parquet as pq

## Normalização dos Dados

A normalização é uma fase crucial do nosso projeto. Os dados que temos contêm muitas informações fora da base binária, o que pode resultar em grandezas fora de escala ao serem comparadas em gráficos.

Para resolver isso, normalizamos nossos dados, definindo um intervalo de 0 a 1. Esse processo garante que os dados mantenham seus valores originais, mas em uma escala comum a todos, facilitando comparações e análises visuais.

Filtramos os times pela Champions League, além de colocarmos os nomes dos player em lowcase

In [3]:
df = pd.read_parquet("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/parquet/appearances.parquet")
df = df[df["competition_id"] == 'CL']
df["player_name"] = df["player_name"].str.lower()
minuscula = lambda x,y: x[y].str.lower()
df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
19861,2262147_103585,2262147,103585,720,1465,2012-09-18,kléber,CL,0,0,0,0,12
19862,2262147_13972,2262147,13972,419,68608,2012-09-18,tonel,CL,0,0,0,0,90
19863,2262147_14098,2262147,14098,720,720,2012-09-18,helton,CL,0,0,0,0,90
19864,2262147_186997,2262147,186997,720,7775,2012-09-18,christian atsu,CL,0,0,0,1,18
19865,2262147_26244,2262147,26244,720,720,2012-09-18,lucho gonzález,CL,0,0,1,0,90

In [4]:
df.describe()
funcao_normaliza1 = lambda x: np.array(df[x], dtype=np.float64)
funcao_normaliza2 = lambda y:(y-y.min())/(y.max()-y.min())
# data_normalizado = (data-data.min())/(data.max()-data.min())
# df["goals"] = data_normalizado
data = funcao_normaliza1("goals")
df["goals"] = funcao_normaliza2(data)
data = funcao_normaliza1("assists")
df["assists"] = funcao_normaliza2(data)
data = funcao_normaliza1("red_cards")
df["red_cards"] = funcao_normaliza2(data)
data = funcao_normaliza1("yellow_cards")
df["yellow_cards"] = funcao_normaliza2(data)
# df.head(10)
table = pa.Table.from_pandas(df)
pq.write_table(table, "C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/apperances_nor.parquet")
table = pq.read_table("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/apperances_nor.parquet")
df = table.to_pandas()

Realizamos o save do dataframe normalizado com os valores na escala correta

In [16]:
# apperances.parquet
df = pd.read_parquet("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/apperances_nor.parquet")
lista_de_jogos = df["game_id"]
df2 = pd.read_parquet("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/parquet/club_games.parquet")
df2["own_manager_name"] = minuscula(df2,"own_manager_name")
df2["opponent_manager_name"] = minuscula(df2,"opponent_manager_name")
filtered_df = df2[df2["game_id"].isin(lista_de_jogos)]
df2 = filtered_df
df = df2
data = funcao_normaliza1("own_goals")
df["own_goals"] = funcao_normaliza2(data)
data = funcao_normaliza1("opponent_goals")
df["opponent_goals"] = funcao_normaliza2(data)
display(df["own_position"])
df["own_position"] = df["own_position"].astype(str).str.replace("NaN", "null")
df["own_position"] = df["own_position"].astype(str).str.replace("nan", "null")
# display(df)
table = pa.Table.from_pandas(df)
pq.write_table(table, "C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/club_games_nor.parquet")
table = pq.read_table("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/club_games_nor.parquet")
df = table.to_pandas()
df.head(20)
# print(lista_de_jogos)

178      NaN
179      NaN
180      NaN
181      NaN
205      NaN
          ..
136409   NaN
136509   NaN
136592   NaN
136685   NaN
136808   NaN
Name: own_position, Length: 2980, dtype: float64

,game_id,club_id,own_goals,own_position,own_manager_name,opponent_id,opponent_goals,opponent_position,opponent_manager_name,hosting,is_win
178,2368445,27,0.625,null,pep guardiola,941,0.000,NaN,pavel vrba,Home,1
179,2368466,371,0.000,null,neil lennon,5,0.375,NaN,massimiliano allegri,Home,0
180,2368478,190,0.000,null,ståle solbakken,418,0.250,NaN,carlo ancelotti,Home,0
181,2368481,683,0.375,null,michel,58,0.125,NaN,john van den brom,Home,1
205,2384520,141,0.125,null,roberto mancini,506,0.000,NaN,antonio conte,Home,1
377,2490853,610,0.125,null,frank de boer,583,0.125,NaN,laurent blanc,Home,0
394,2495298,336,0.000,null,marco silva,631,0.125,NaN,josé mourinho,Home,0
395,2495311,12,0.125,null,rudi garcia,27,0.875,NaN,pep guardiola,Home,0
396,2495361,418,0.500,null,carlo ancelotti,31614,0.000,NaN,georgi dermendzhiev,Home,1
397,2495365,16,0.125,null,jürgen klopp,58,0.125,NaN,besnik hasi,Home,0
398,2495373,621,0.250,null,ernesto valverde,713,0.000,NaN,aleksandr ermakovich,Home,1
434,2517527,720,0.500,null,julen lopetegui,26,0.000,NaN,paulo sousa,Home,1
647,2618536,418,0.500,null,rafael benítez,660,0.000,NaN,mircea lucescu,Home,1
648,2618544,12,0.125,null,rudi garcia,131,0.125,NaN,luis enrique,Home,0
649,2618567,985,0.250,null,louis van gaal,82,0.125,NaN,dieter hecking,Home,1
650,2618580,11,0.250,null,arsène wenger,27,0.000,NaN,pep guardiola,Home,1
651,2618604,27,0.625,null,pep guardiola,11,0.125,NaN,arsène wenger,Home,1
652,2618615,22220,0.250,null,stanimir stoilov,294,0.250,NaN,rui vitória,Home,0
714,2675294,27,0.125,null,pep guardiola,294,0.000,NaN,rui vitória,Home,1
715,2675295,131,0.250,null,luis enrique,13,0.125,NaN,diego simeone,Home,1

In [42]:
#clubs.parquet
df = pd.read_parquet("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/parquet/clubs.parquet")
df["name"] = minuscula(df,"name")
df["stadium_name"] = minuscula(df,"stadium_name")
data = funcao_normaliza1("squad_size")
df["squad_size"] = funcao_normaliza2(data)
data = funcao_normaliza1("foreigners_number")
df["foreigners_number"] = funcao_normaliza2(data)
data = funcao_normaliza1("national_team_players")
df["national_team_players"] = funcao_normaliza2(data)
data = funcao_normaliza1("stadium_seats")
df["stadium_seats"] = funcao_normaliza2(data)
df["total_market_value"] = df["total_market_value"].astype(str).str.replace("NaN", "null")
df["total_market_value"] = df["total_market_value"].astype(str).str.replace("nan", "null")
df["foreigners_percentage"] = df["foreigners_percentage"].astype(str).str.replace("nan", "null")
df["average_age"] = df["average_age"].astype(str).str.replace("NaN", "null")
df["coach_name"] = df["coach_name"].astype(str).str.replace("nan", "null")
nulls_per_column = df.isnull().sum()

print("Número de nulos em cada coluna:")
print(nulls_per_column)
df.head(20)

table = pa.Table.from_pandas(df)
pq.write_table(table, "C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/club_nor.parquet")
table = pq.read_table("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/club_nor.parquet")
df = table.to_pandas()

Número de nulos em cada coluna:
club_id                    0
club_code                  0
name                       0
domestic_competition_id    0
total_market_value         0
squad_size                 0
average_age                0
foreigners_number          0
foreigners_percentage      0
national_team_players      0
stadium_name               0
stadium_seats              0
net_transfer_record        0
coach_name                 0
last_season                0
filename                   0
url                        0
dtype: int64

In [46]:
#competitions.parquet
df = pd.read_parquet("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/parquet/competitions.parquet")
df = df[df["competition_id"] == 'CL']
df["country_name"] = df["country_name"].astype(str).str.replace("None", "null")
df["domestic_league_code"] = df["domestic_league_code"].astype(str).str.replace("None", "null")
table = pa.Table.from_pandas(df)
pq.write_table(table, "C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/competitions_nor.parquet")
table = pq.read_table("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/competitions_nor.parquet")
df = table.to_pandas()
df.head(20)

,competition_id,competition_code,name,sub_type,type,country_id,country_name,domestic_league_code,confederation,url,is_major_national_league
27,CL,uefa-champions-league,uefa-champions-league,uefa_champions_league,international_cup,-1,null,null,europa,https://www.transfermarkt.co.uk/uefa-champions...,False

In [65]:
#games_events.parquet
df = pd.read_parquet("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/parquet/game_events.parquet")
df["type"] = df["type"].str.lower()
df["description"] = df["description"].str.lower()
data = funcao_normaliza1("minute")
df["minute"] = funcao_normaliza2(data)
df["description"] = df["description"].astype(str).str.replace("NaN", "null") #
df["description"] = df["description"].astype(str).str.replace(", not reported", "null")
df["description"] = df["description"].astype(str).str.replace("NaN", "null")
df["player_in_id"] = df["player_in_id"].astype(str).str.replace("NaN", "null") 
df["player_in_id"] = df["player_in_id"].astype(str).str.replace("NaN", "null")
df["player_in_id"] = df["player_in_id"].astype(str).str.replace("nan", "null")
df["player_in_id"] = df["player_in_id"].astype(str).str.replace("NaN", "null")
df["player_assist_id"] = df["player_assist_id"].astype(str).str.replace("nan", "null")

nulls_per_column = df.isnull().sum()
print("Número de nulos em cada coluna:")
print(nulls_per_column)

table = pa.Table.from_pandas(df)
pq.write_table(table, "C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/games_events_nor.parquet")
table = pq.read_table("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/games_events_nor.parquet")
df = table.to_pandas()

df.head(20)
# df.tail(20)

Número de nulos em cada coluna:
game_event_id       0
date                0
game_id             0
minute              0
type                0
club_id             0
player_id           0
description         0
player_in_id        0
player_assist_id    0
dtype: int64

,game_event_id,date,game_id,minute,type,club_id,player_id,description,player_in_id,player_assist_id
0,2f41da30c471492e7d4a984951671677,2012-08-05,2211607,0.644628,cards,610,4425,"1. yellow card , mass confrontation",null,null
1,a72f7186d132775f234d3e2f7bc0ed5b,2012-08-05,2211607,0.644628,cards,383,33210,"1. yellow card , mass confrontation",null,null
2,b2d721eaed4692a5c59a92323689ef18,2012-08-05,2211607,0.033058,goals,383,36500,", header, 1. tournament goal assist: , corner,...",null,56416.0
3,aef768899cedac0c9a650980219075a2,2012-08-05,2211607,0.446281,goals,383,36500,", right-footed shot, 2. tournament goal assist...",null,146258.0
4,5d6d9533023057b6619ecd145a038bbe,2012-08-05,2211607,0.619835,substitutions,383,36500,null,49499.0,null
5,eef9c46dd75c3aa4c6a503225427446e,2012-08-05,2211607,0.099174,goals,383,38497,", right-footed shot, 1. tournament goal assist...",null,33210.0
6,5d5aef7dedcd5dc9d35dea9438ee35e0,2012-08-05,2211607,0.752066,cards,610,42710,1. yellow card,null,null
7,7717860e3b0376b86f445f4749fa2ce5,2012-08-05,2211607,0.371901,goals,610,42710,", header, 1. tournament goal assist: , corner,...",null,4425.0
8,02c708273f4fa2003873ef5908e4e3a6,2012-08-05,2211607,0.661157,cards,610,45509,1. yellow card,null,null
9,d1be2ce4bd5f0ca091c1b15a8569301c,2012-08-05,2211607,0.752066,goals,383,49499,", right-footed shot, 1. tournament goal assist...",null,167850.0
10,f0dfb41b779ad8efbd5acbd0aeedff11,2012-08-05,2211607,0.636364,substitutions,610,52246,null,182932.0,null
11,06d75371c9a8f3a8db9236ffdd01dcb1,2012-08-05,2211607,0.628099,goals,610,52920,", own-goal assist: , cross, 1. tournament assist",null,124891.0
12,6ab3a43a37e3b264d03dcf997e38c167,2012-08-05,2211607,0.314050,cards,383,68864,1. yellow card,null,null
13,e67340caefbf1cbe1be393d3d61448e1,2012-08-05,2211607,0.702479,substitutions,383,72462,null,167850.0,null
14,ac69368250666fd5e9d142f53f1e539f,2012-08-05,2211607,0.545455,substitutions,610,95755,null,34784.0,null
15,874987f117bca74599041037e0c43075,2012-08-05,2211607,0.000000,cards,610,124883,1. yellow card,null,null
16,c7273eb67de6f9ba953ae41e7bffb62a,2012-08-05,2211607,0.264463,cards,610,187245,1. yellow card,null,null
17,584282a7024a5a6da90cbb20317111ff,2012-08-05,2211607,0.636364,substitutions,610,187245,null,111184.0,null
18,ed9bded6064e693d92634a764cfd3e1a,2012-08-11,2218677,0.636364,cards,506,2865,1. yellow card,null,null
19,fead616bb25013d5cb15d9fe7f12880e,2012-08-11,2218677,0.743802,substitutions,506,2865,null,56703.0,null

In [69]:
#game_lineups.parquet
df = pd.read_parquet("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/parquet/game_lineups.parquet")
df["player_name"] = df["player_name"].str.lower()
df["position"] = df["position"].str.lower()
df["position"] = df["position"].astype(str).str.replace("NaN", "null")
df["position"] = df["position"].astype(str).str.replace("nan", "null")

nulls_per_column = df.isnull().sum()
print("Número de nulos em cada coluna:")
print(nulls_per_column)

table = pa.Table.from_pandas(df)
pq.write_table(table, "C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/game_lineups_nor.parquet")
table = pq.read_table("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/game_lineups_nor.parquet")
df = table.to_pandas()

df.head(20)

Número de nulos em cada coluna:
game_lineups_id    0
date               0
game_id            0
player_id          0
club_id            0
player_name        0
type               0
position           0
number             0
team_captain       0
dtype: int64

,game_lineups_id,date,game_id,player_id,club_id,player_name,type,position,number,team_captain
0,b2dbe01c3656b06c8e23e9de714e26bb,2013-07-27,2317258,1443,610,christian poulsen,substitutes,defensive midfield,5,0
1,b50a3ec6d52fd1490aab42042ac4f738,2013-07-27,2317258,5017,610,niklas moisander,starting_lineup,centre-back,4,0
2,7d890e6d0ff8af84b065839966a0ec81,2013-07-27,2317258,9602,1090,maarten martens,substitutes,left winger,11,0
3,8c355268678b9bbc7084221b1f0fde36,2013-07-27,2317258,12282,610,daley blind,starting_lineup,left-back,17,0
4,76193074d549e5fdce4cdcbba0d66247,2013-07-27,2317258,25427,1090,roy beerens,starting_lineup,right winger,23,0
5,e5684d3b01123e27e738a6c7ed1c24cc,2013-07-27,2317258,28815,1090,jan wuytens,starting_lineup,centre-back,29,0
6,d196e3ec2f03110a523b6eaa65027f07,2013-07-27,2317258,30290,610,kenneth vermeer,starting_lineup,goalkeeper,1,0
7,e9e1212e3ba0dabdf39f45ce631799f7,2013-07-27,2317258,34784,610,lasse schöne,starting_lineup,defensive midfield,20,0
8,53ca254113ffc1b2f4533b0e334c9a15,2013-07-27,2317258,36391,1090,viktor elm,starting_lineup,defensive midfield,12,0
9,03fe553a31b7cc907330b989c060b5cc,2013-07-27,2317258,42266,1090,yves de winter,substitutes,goalkeeper,16,0
10,1412e8a9285378507537c6346c77c6ff,2013-07-27,2317258,42710,610,toby alderweireld,starting_lineup,centre-back,3,0
11,55159dbf91561a01ba94bd9d61c6d33d,2013-07-27,2317258,44675,610,bojan krkic,starting_lineup,right winger,11,0
12,be9fbdcde744131e27d57f1ad13bbfd7,2013-07-27,2317258,45509,610,siem de jong,starting_lineup,attacking midfield,10,1
13,d25d1f3a4bd28e3b99f28f8f93781de0,2013-07-27,2317258,52246,610,kolbeinn sigthórsson,starting_lineup,centre-forward,9,0
14,d51bc97b0db40f004acb5c66e4e609ed,2013-07-27,2317258,56534,1090,donny gorter,substitutes,left-back,5,0
15,ac1c4c90cf314ad3f4f247be447acba9,2013-07-27,2317258,69633,610,christian eriksen,starting_lineup,central midfield,8,0
16,091c126bd4e71488db374cb2958ae89e,2013-07-27,2317258,69642,610,nicolai boilesen,substitutes,left-back,15,0
17,37f4184cf76506a50eab234280d99765,2013-07-27,2317258,74294,1090,nemanja gudelj,starting_lineup,central midfield,27,0
18,d4c2262dc4bacc63d59810193c51e4f8,2013-07-27,2317258,80709,1090,willie overtoom,substitutes,attacking midfield,10,0
19,4c0ba30ea80ef6c582506eecf284f788,2013-07-27,2317258,81163,610,danny hoesen,substitutes,centre-forward,23,0

In [111]:
#games.parquet
df = pd.read_parquet("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/parquet/games.parquet")
df = df[df["competition_id"] == 'CL']
df["home_club_name"] = df["home_club_name"].str.lower()
df["stadium"] = df["stadium"].str.lower()
df["round"] = df["round"].str.lower()
df["home_club_position"] = df["home_club_position"].astype(str).str.replace("NaN", "null")
df["home_club_position"] = df["home_club_position"].astype(str).str.replace("nan", "null")
df["away_club_position"] = df["away_club_position"].astype(str).str.replace("NaN", "null")
df["away_club_position"] = df["away_club_position"].astype(str).str.replace("nan", "null")
df["stadium "] = df["stadium"].astype(str).str.replace("NaN", "null")
df["stadium "] = df["stadium"].astype(str).str.replace("nan", "null")
df["attendance"] = df["attendance"].astype(str).str.replace("NaN", "null")
df["attendance"] = df["attendance"].astype(str).str.replace("nan", "null")
df["referee"] = df["referee"].astype(str).str.replace("NaN", "null")
df["referee"] = df["referee"].astype(str).str.replace("nan", "null")
df["home_club_formation"] = df["home_club_formation"].astype(str).str.replace("NaN", "null")
df["home_club_formation"] = df["home_club_formation"].astype(str).str.replace("nan", "null")
df["away_club_formation"] = df["away_club_formation"].astype(str).str.replace("NaN", "null")
df["away_club_formation"] = df["away_club_formation"].astype(str).str.replace("nan", "null")
df["home_club_name"] = df["home_club_name"].astype(str).str.replace("NaN", "null")
df["home_club_name"] = df["home_club_name"].astype(str).str.replace("nan", "null")
df["away_club_name"] = df["away_club_name"].astype(str).str.replace("NaN", "null")
df["away_club_name"] = df["away_club_name"].astype(str).str.replace("nan", "null")
# data = funcao_normaliza1("away_club_goals")
# df["away_club_goals"] = funcao_normaliza2(data)
# data = funcao_normaliza1("home_club_goals")
# df["home_club_goals"] = funcao_normaliza2(data)
# df["home_club_position"] = df["home_club_position"].str.lower()
# df["away_manager_name"] = df["away_manager_name"].str.lower()

nulls_per_column = df.isnull().sum()
print("Número de nulos em cada coluna:")
print(nulls_per_column)

table = pa.Table.from_pandas(df)
pq.write_table(table, "C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/games.parquet_nor.parquet")
table = pq.read_table("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/games.parquet_nor.parquet")
df = table.to_pandas()


df.head(20)

Número de nulos em cada coluna:
game_id                   0
competition_id            0
season                    0
round                     0
date                      0
home_club_id              0
away_club_id              0
home_club_goals           0
away_club_goals           0
home_club_position        0
away_club_position        0
home_club_manager_name    0
away_club_manager_name    0
stadium                   3
attendance                0
referee                   0
url                       0
home_club_formation       0
away_club_formation       0
home_club_name            0
away_club_name            0
aggregate                 0
competition_type          0
stadium                   0
dtype: int64

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type,stadium
105,2368466,CL,2013,group h,2013-11-26,371,5,0,3,null,...,58619.0,Cüneyt Cakir,https://www.transfermarkt.co.uk/spielbericht/i...,4-2-3-1,4-3-2-1,celtic fc,AC Milan,0:3,international_cup,celtic park
106,2368481,CL,2013,group c,2013-12-10,683,58,3,1,null,...,31444.0,Wolfgang Stark,https://www.transfermarkt.co.uk/spielbericht/i...,4-4-1-1,4-1-4-1,olympiacos piraeus,RSC Anderlecht,3:1,international_cup,stadio georgios karaiskakis
111,2384520,CL,2013,group b,2013-12-11,141,506,1,0,null,...,37375.0,Pedro Proença,https://www.transfermarkt.co.uk/spielbericht/i...,3-5-2,3-5-2 flat,galatasaray,Juventus FC,1:0,international_cup,ali sami yen spor kompleksi rams park
212,2490853,CL,2014,group f,2014-09-17,610,583,1,1,null,...,50430.0,Wolfgang Stark,https://www.transfermarkt.co.uk/spielbericht/i...,4-3-3 Attacking,4-3-3 Attacking,ajax amsterdam,Paris Saint-Germain,1:1,international_cup,johan cruijff arena
222,2495311,CL,2014,group e,2014-10-21,12,27,1,7,null,...,62292.0,Jonas Eriksson,https://www.transfermarkt.co.uk/spielbericht/i...,4-3-3 Attacking,3-5-2,as roma,Bayern Munich,1:7,international_cup,olimpico di roma
223,2495365,CL,2014,group d,2014-12-09,16,58,1,1,null,...,65829.0,Undiano Mallenco,https://www.transfermarkt.co.uk/spielbericht/i...,4-2-3-1,4-2-3-1,borussia dortmund,RSC Anderlecht,1:1,international_cup,signal iduna park
364,2618544,CL,2015,group e,2015-09-16,12,131,1,1,null,...,57836.0,Björn Kuipers,https://www.transfermarkt.co.uk/spielbericht/i...,4-3-3 Attacking,4-3-3 Attacking,as roma,FC Barcelona,1:1,international_cup,olimpico di roma
365,2618567,CL,2015,group b,2015-09-30,985,82,2,1,null,...,70000.0,Viktor Kassai,https://www.transfermarkt.co.uk/spielbericht/i...,4-2-3-1,4-2-3-1,manchester united,VfL Wolfsburg,2:1,international_cup,old trafford
366,2618580,CL,2015,group f,2015-10-20,11,27,2,0,null,...,60000.0,Cüneyt Cakir,https://www.transfermarkt.co.uk/spielbericht/i...,4-2-3-1,4-3-3 Attacking,arsenal fc,Bayern Munich,2:0,international_cup,emirates stadium
367,2618604,CL,2015,group f,2015-11-04,27,11,5,1,null,...,70000.0,Gianluca Rocchi,https://www.transfermarkt.co.uk/spielbericht/i...,4-2-3-1,4-4-2 double 6,bayern munich,Arsenal FC,5:1,international_cup,allianz arena
397,2675294,CL,2015,quarter-finals 1st leg,2016-04-05,27,294,1,0,null,...,70000.0,Szymon Marciniak,https://www.transfermarkt.co.uk/spielbericht/i...,4-4-2 double 6,4-4-2 double 6,bayern munich,SL Benfica,1:0,international_cup,allianz arena
398,2675295,CL,2015,quarter-finals 1st leg,2016-04-05,131,13,2,1,null,...,88534.0,Dr. Felix Brych,https://www.transfermarkt.co.uk/spielbericht/i...,4-3-3 Attacking,4-4-2 double 6,fc barcelona,Atlético de Madrid,2:1,international_cup,spotify camp nou
501,2754918,CL,2016,group c,2016-10-19,371,18,0,2,null,...,57814.0,Anastasios Sidiropoulos,https://www.transfermarkt.co.uk/spielbericht/i...,4-2-3-1,4-2-3-1,celtic fc,Borussia Mönchengladbach,0:2,international_cup,celtic park
610,2917360,CL,2017,group b,2017-09-12,371,583,0,5,null,...,57562.0,Daniele Orsato,https://www.transfermarkt.co.uk/spielbericht/i...,4-2-3-1,4-3-3 Attacking,celtic fc,Paris Saint-Germain,0:5,international_cup,celtic park
611,2917362,CL,2017,group c,2017-09-12,12,13,0,0,null,...,36064.0,Milorad Mazic,https://www.transfermarkt.co.uk/spielbericht/i...,4-1-4-1,4-4-2,as roma,Atlético de Madrid,0:0,international_cup,olimpico di roma
612,2917391,CL,2017,group b,2017-10-18,58,583,0,4,null,...,19106.0,Pavel Kralovec,https://www.transfermarkt.co.uk/spielbericht/i...,3-4-2-1,4-3-3 Attacking,rsc anderlecht,Paris Saint-Germain,0:4,international_cup,constant vanden stock stadion
613,2917441,CL,2017,group c,2017-12-05,631,13,1,1,null,...,40875.0,Danny Makkelie,https://www.transfermarkt.co.uk/spielbericht/i...,3-5-2 flat,4-4-2,chelsea fc,Atlético de Madrid,1:1,international_cup,stamford bridge
659,2367096,CL,2013,group f,2013-09-18,6195,16,2,1,null,...,55766.0,Pedro Proença,https://www.transfermarkt.co.uk/spielbericht/i...,4-2-3-1,4-2-3-1,ssc napoli,Borussia Dortmund,2:1,international_cup,stadio diego armando maradona
661,2368442,CL,2013,group b,2013-10-23,141,190,3,1,null,...,42798.0,Aleksandar Stavrev,https://www.transfermarkt.co.uk/spielbericht/i...,4-2-3-1,4-4-2,galatasaray,FC Copenhagen,3:1,international_cup,ali sami yen spor kompleksi rams park
662,2368487,CL,2013,group f,2013-12-11,244,16,1,2,null,...,36655.0,Marijo Strahonja,https://www.transfermarkt.co.uk/spielbericht/i...,4-2-3-1,4-2-3-1,olympique marseille,Borussia Dortmund,1:2,international_cup,orange vélodrome

In [139]:
#playe_values.parquet
df = pd.read_parquet("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/parquet/player_valuations.parquet")
# df["player_club_domestic_competition_id"] = df["player_club_domestic_competition_id"].str.lower()
data = funcao_normaliza1("market_value_in_eur")
df["market_value_in_eur"] = funcao_normaliza2(data)
table = pa.Table.from_pandas(df)
pq.write_table(table, "C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/player_valuations_nor.parquet")
table = pq.read_table("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/player_valuations_nor.parquet")
df = table.to_pandas()

nulls_per_column = df.isnull().sum()
print("Número de nulos em cada coluna:")
print(nulls_per_column)
df.head(20)

Número de nulos em cada coluna:
player_id                              0
date                                   0
market_value_in_eur                    0
current_club_id                        0
player_club_domestic_competition_id    0
dtype: int64

,player_id,date,market_value_in_eur,current_club_id,player_club_domestic_competition_id
0,405973,2000-01-20,0.00075,3057,BE1
1,342216,2001-07-20,0.00050,1241,SC1
2,3132,2003-12-09,0.00200,126,TR1
3,6893,2003-12-15,0.00450,984,GB1
4,10,2004-10-04,0.03500,398,IT1
5,26,2004-10-04,0.00750,16,L1
6,65,2004-10-04,0.04000,1091,GR1
7,77,2004-10-04,0.06500,506,IT1
8,80,2004-10-04,0.00200,27,L1
9,109,2004-10-04,0.04750,825,TR1
10,123,2004-10-04,0.04750,33,L1
11,132,2004-10-04,0.06500,11,GB1
12,162,2004-10-04,0.00625,79,L1
13,215,2004-10-04,0.03750,1084,ES1
14,264,2004-10-04,0.00125,79,L1
15,276,2004-10-04,0.00125,20100,DK1
16,277,2004-10-04,0.00625,3368,ES1
17,299,2004-10-04,0.04500,10484,TR1
18,325,2004-10-04,0.04000,141,TR1
19,332,2004-10-04,0.00125,24,L1

In [140]:
#players.parquet
df = pd.read_parquet("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/parquet/players.parquet")
min
df["first_name"] = df["first_name"].str.lower()
df["last_name"] = df["last_name"].str.lower()
df["name"] = df["name"].str.lower()
df["country_of_birth"] = df["country_of_birth"].str.lower()
df["country_of_birth"] = df["country_of_birth"].str.lower()
df["city_of_birth"] = minuscula(df,"city_of_birth")
df["country_of_citizenship"] = minuscula(df,"country_of_citizenship")
df["foot"] = minuscula(df,"foot")
df["agent_name"] = minuscula(df,"agent_name")
# df["current_club_domestic_competition_id"] = minuscula(df,"current_club_domestic_competition_id")
df["current_club_name"] = minuscula(df,"current_club_name")


df["first_name"] = df["first_name"].astype(str).str.replace("NaN", "null")
df["first_name"] = df["first_name"].astype(str).str.replace("nan", "null")
df["first_name"] = df["first_name"].astype(str).str.replace("None", "null")
df["country_of_birth"] = df["country_of_birth"].astype(str).str.replace("NaN", "null")
df["country_of_birth"] = df["country_of_birth"].astype(str).str.replace("nan", "null")
df["country_of_birth"] = df["country_of_birth"].astype(str).str.replace("None", "null")
df["city_of_birth"] = df["city_of_birth"].astype(str).str.replace("NaN", "null")
df["city_of_birth"] = df["city_of_birth"].astype(str).str.replace("nan", "null")
df["city_of_birth"] = df["city_of_birth"].astype(str).str.replace("None", "null")
df["country_of_citizenship"] = df["country_of_citizenship"].astype(str).str.replace("NaN", "null")
df["country_of_citizenship"] = df["country_of_citizenship"].astype(str).str.replace("nan", "null")
df["country_of_citizenship"] = df["country_of_citizenship"].astype(str).str.replace("None", "null")
df["foot"] = df["foot"].astype(str).str.replace("NaN", "null")
df["foot"] = df["foot"].astype(str).str.replace("nan", "null")
df["foot"] = df["foot"].astype(str).str.replace("None", "null")
df["agent_name"] = df["agent_name"].astype(str).str.replace("NaN", "null")
df["agent_name"] = df["agent_name"].astype(str).str.replace("nan", "null")
df["agent_name"] = df["agent_name"].astype(str).str.replace("None", "null")
df["date_of_birth"] = df["date_of_birth"].astype(str).str.replace("NaN", "null")
df["date_of_birth"] = df["date_of_birth"].astype(str).str.replace("nan", "null")
df["date_of_birth"] = df["date_of_birth"].astype(str).str.replace("None", "null")
df["sub_position"] = df["sub_position"].astype(str).str.replace("NaN", "null")
df["sub_position"] = df["sub_position"].astype(str).str.replace("nan", "null")
df["sub_position"] = df["sub_position"].astype(str).str.replace("None", "null")
df["height_in_cm"] = df["height_in_cm"].astype(str).str.replace("NaN", "null")
df["height_in_cm"] = df["height_in_cm"].astype(str).str.replace("nan", "null")
df["height_in_cm"] = df["height_in_cm"].astype(str).str.replace("None", "null")
df["contract_expiration_date"] = df["contract_expiration_date"].astype(str).str.replace("NaN", "null")
df["contract_expiration_date"] = df["contract_expiration_date"].astype(str).str.replace("nan", "null")
df["contract_expiration_date"] = df["contract_expiration_date"].astype(str).str.replace("None", "null")
df["agent_name"] = df["agent_name"].astype(str).str.replace("NaN", "null")
df["agent_name"] = df["agent_name"].astype(str).str.replace("nan", "null")
df["agent_name"] = df["agent_name"].astype(str).str.replace("None", "null")
df["market_value_in_eur"] = df["market_value_in_eur"].astype(str).str.replace("NaN", "0")
df["market_value_in_eur"] = df["market_value_in_eur"].astype(str).str.replace("nan", "0")
df["market_value_in_eur"] = df["market_value_in_eur"].astype(str).str.replace("None", "0")
df["highest_market_value_in_eur"] = df["highest_market_value_in_eur"].astype(str).str.replace("NaN", "0")
df["highest_market_value_in_eur"] = df["highest_market_value_in_eur"].astype(str).str.replace("nan","0")
df["highest_market_value_in_eur"] = df["highest_market_value_in_eur"].astype(str).str.replace("None", "0")

data = df["market_value_in_eur"]
data = pd.Series(data).replace('null', '0')
data = funcao_normaliza1("market_value_in_eur")
df["market_value_in_eur"] = funcao_normaliza2(data)

data = df["highest_market_value_in_eur"]
data = pd.Series(data).replace('null', '0')
data = funcao_normaliza1("highest_market_value_in_eur")
df["highest_market_value_in_eur"] = funcao_normaliza2(data)


nulls_per_column = df.isnull().sum()
print("Número de nulos em cada coluna:")
print(nulls_per_column)

table = pa.Table.from_pandas(df)
pq.write_table(table, "C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/players_nor.parquet")
table = pq.read_table("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/players_nor.parquet")
df = table.to_pandas()


df.head(20)

Número de nulos em cada coluna:
player_id                               0
first_name                              0
last_name                               0
name                                    0
last_season                             0
current_club_id                         0
player_code                             0
country_of_birth                        0
city_of_birth                           0
country_of_citizenship                  0
date_of_birth                           0
sub_position                            0
position                                0
foot                                    0
height_in_cm                            0
contract_expiration_date                0
agent_name                              0
image_url                               0
url                                     0
current_club_domestic_competition_id    0
current_club_name                       0
market_value_in_eur                     0
highest_market_value_in_eur             0
dtype: int64

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,miroslav,klose,miroslav klose,2015,398,miroslav-klose,poland,opole,germany,...,right,184.0,null,asbw sport marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,ss lazio,0.005556,0.15000
1,26,roman,weidenfeller,roman weidenfeller,2017,16,roman-weidenfeller,germany,diez,germany,...,left,190.0,null,neubauer 13 gmbh,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,borussia dortmund,0.004167,0.04000
2,65,dimitar,berbatov,dimitar berbatov,2015,1091,dimitar-berbatov,bulgaria,blagoevgrad,bulgaria,...,null,null,null,cska-as-23 ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,paok thessaloniki,0.005556,0.17250
3,77,null,lúcio,lúcio,2012,506,lucio,brazil,brasília,brazil,...,null,null,null,null,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,juventus fc,0.001111,0.12250
4,80,tom,starke,tom starke,2017,27,tom-starke,east germany (gdr),freital,germany,...,right,194.0,null,ifm,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,bayern munich,0.000556,0.01500
5,109,null,dedê,dedê,2013,825,dede,brazil,belo horizonte,brazil,...,null,null,null,football concept,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dede/profil/sp...,TR1,eskisehirspor,0.002222,0.04750
6,123,christoph,metzelder,christoph metzelder,2012,33,christoph-metzelder,germany,haltern,germany,...,null,null,null,null,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/christoph-metz...,L1,fc schalke 04,0.008333,0.04750
7,132,tomas,rosicky,tomas rosicky,2015,11,tomas-rosicky,cssr,praha,czech republic,...,both,179.0,null,null,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tomas-rosicky/...,GB1,arsenal fc,0.001944,0.08750
8,162,marc,ziegler,marc ziegler,2012,79,marc-ziegler,germany,blieskastel,germany,...,right,193.0,null,null,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/marc-ziegler/p...,L1,vfb stuttgart,0.001111,0.00625
9,215,roque,santa cruz,roque santa cruz,2015,1084,roque-santa-cruz,paraguay,asunción,paraguay,...,right,193.0,2023-12-31 00:00:00,null,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roque-santa-cr...,ES1,málaga cf,0.001389,0.06000
10,258,gerald,asamoah,gerald asamoah,2013,33,gerald-asamoah,ghana,mampong,germany,...,right,180.0,null,null,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/gerald-asamoah...,L1,fc schalke 04,0.000556,0.03500
11,264,tamás,hajnal,tamás hajnal,2012,79,tamas-hajnal,hungary,esztergom,hungary,...,both,167.0,null,null,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tamas-hajnal/p...,L1,vfb stuttgart,0.000556,0.03250
12,276,sladan,peric,sladan peric,2013,20100,sladan-peric,null,null,denmark,...,null,null,null,null,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/sladan-peric/p...,DK1,fc vestsjaelland,0.001111,0.00250
13,277,sérgio,da silva pinto,sérgio da silva pinto,2013,3368,sergio-da-silva-pinto,portugal,vila nova de gaia,germany,...,right,176.0,null,null,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/sergio-da-silv...,ES1,levante ud,0.000833,0.01750
14,299,fabian,ernst,fabian ernst,2012,10484,fabian-ernst,germany,hannover,germany,...,right,183.0,null,null,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/fabian-ernst/p...,TR1,kasimpasa,0.008333,0.04500
15,325,tomas,ujfalusi,tomas ujfalusi,2012,141,tomas-ujfalusi,cssr,rýmařov,czech republic,...,null,null,null,null,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tomas-ujfalusi...,TR1,galatasaray,0.001667,0.06000
16,332,benjamin,köhler,benjamin köhler,2012,24,benjamin-kohler,germany,berlin,germany,...,null,null,null,null,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/benjamin-kohle...,L1,eintracht frankfurt,0.000833,0.01250
17,410,sebastian,kehl,sebastian kehl,2014,16,sebastian-kehl,germany,fulda,germany,...,left,187.0,null,null,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/sebastian-kehl...,L1,borussia dortmund,0.005556,0.04500
18,411,levan,kobiashvili,levan kobiashvili,2013,44,levan-kobiashvili,udssr,tiflis,georgia,...,left,183.0,null,null,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/levan-kobiashv...,L1,hertha bsc,0.002222,0.03750
19,447,oka,nikolov,oka nikolov,2012,24,oka-nikolov,germany,erbach im odenwald,north macedonia,...,right,188.0,null,pro profil gmbh,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/oka-nikolov/pr...,L1,eintracht frankfurt,0.001944,0.01000

In [138]:
#transfers.parquet
df = pd.read_parquet("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/parquet/transfers.parquet")
df["from_club_name"] = minuscula(df,"from_club_name")  
df["to_club_name"] = minuscula(df,"to_club_name")
df["player_name"] = minuscula(df,"player_name")
df["market_value_in_eur"] = df["market_value_in_eur"].astype(str).str.replace("NaN", "0")
df["market_value_in_eur"] = df["market_value_in_eur"].astype(str).str.replace("nan","0")
df["market_value_in_eur"] = df["market_value_in_eur"].astype(str).str.replace("None", "0")
df["transfer_fee"] = df["transfer_fee"].astype(str).str.replace("NaN", "0")
df["transfer_fee"] = df["transfer_fee"].astype(str).str.replace("nan", "0")
df["transfer_fee"] = df["transfer_fee"].astype(str).str.replace("None", "0")

data = df["market_value_in_eur"]
data = pd.Series(data).replace('null', '0')
data = funcao_normaliza1("market_value_in_eur")
df["market_value_in_eur"] = funcao_normaliza2(data)

data = df["transfer_fee"]
data = pd.Series(data).replace('null', '0')
data = funcao_normaliza1("transfer_fee")
df["transfer_fee"] = funcao_normaliza2(data)

nulls_per_column = df.isnull().sum()
print("Número de nulos em cada coluna:")
print(nulls_per_column)

table = pa.Table.from_pandas(df)
pq.write_table(table, "C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/transfers_nor.parquet")
table = pq.read_table("C:/Users/maini/dir/PISI-III/pullebyte-analises/DataSet Project/football-transfermarkt-dataset-01/dados_nomalizados/transfers_nor.parquet")
df = table.to_pandas()

df.head(20)

Número de nulos em cada coluna:
player_id              0
transfer_date          0
transfer_season        0
from_club_id           0
to_club_id             0
from_club_name         0
to_club_name           0
transfer_fee           0
market_value_in_eur    0
player_name            0
dtype: int64

,player_id,transfer_date,transfer_season,from_club_id,to_club_id,from_club_name,to_club_name,transfer_fee,market_value_in_eur,player_name
0,195778,2026-06-30,25/26,79,27,vfb stuttgart,bayern munich,0.000000,0.066667,alexander nübel
1,360791,2025-12-31,25/26,6418,1030,panetolikos,argentinos jrs.,0.000000,0.006667,lucas chaves
2,731491,2025-12-31,25/26,209,46,river plate,inter,0.000000,0.005000,franco carboni
3,1038821,2025-07-31,25/26,3837,11204,fredrikstad,stade reims b,0.000000,0.000556,fallou fall
4,229817,2025-07-01,25/26,1083,515,rostov,without club,0.000000,0.009444,ali sowe
5,301238,2025-07-01,25/26,2919,506,monza,juventus,0.079444,0.100000,michele di gregorio
6,1003295,2025-07-01,25/26,15642,1177,silkeborg u19,silkeborg if,0.000000,0.000000,julius nielsen
7,59047,2025-06-30,24/25,101362,53646,pfk zvyagel,polissya,0.000000,0.000556,vasyl grytsuk
8,80444,2025-06-30,24/25,978,405,vasco da gama,aston villa,0.000000,0.041667,philippe coutinho
9,81173,2025-06-30,24/25,409,23826,rb salzburg,rb leipzig,0.000000,0.011111,janis blaswich
10,88706,2025-06-30,24/25,1038,8970,sampdoria,frosinone,0.000000,0.004444,simone romagnoli
11,115763,2025-06-30,24/25,1467,276,göztepe,hellas verona,0.000000,0.004722,koray günter
12,131951,2025-06-30,24/25,332,276,bari,hellas verona,0.000000,0.005278,kevin lasagna
13,148928,2025-06-30,24/25,368,13,sevilla fc,atlético madrid,0.000000,0.041667,saúl ñíguez
14,167799,2025-06-30,24/25,244,148,marseille,tottenham,0.000000,0.100000,pierre-emile højbjerg
15,170527,2025-06-30,24/25,148,23826,tottenham,rb leipzig,0.000000,0.094444,timo werner
16,177847,2025-06-30,24/25,472,368,ud las palmas,sevilla fc,0.000000,0.011111,adnan januzaj
17,178314,2025-06-30,24/25,75231,41231,dinamo makhach.,sochi,0.000000,0.004444,victorien angban
18,200188,2025-06-30,24/25,2581,252,mantova,genoa,0.000000,0.007222,mattia aramu
19,205128,2025-06-30,24/25,385,200,fortuna sittard,fc utrecht,0.000000,0.003333,mattijs branderhorst